In [1]:
from PIL import Image
import os
import csv

In [2]:
maindirectory = os.getcwd()
print(os.getcwd())
#os.chdir("./python_images/iu")#set current directory to the directory of images

C:\Users\Jae\Documents\GitHub\rgb_to_grayscale


In [3]:
os.chdir(maindirectory + "/python_images/iu")
imagelist = sorted(os.listdir())
rgblist = []

for image in imagelist[:4]:
    try:
        im = Image.open(image)
        pix = im.load()        
        x = im.size[0]#gettin x
        y = im.size[1]#getting y
        print(im)
        for i in range(x):
            for j in range(y):
                rgblist.append(pix[i, j])
    except:
        continue
        

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1920x1200 at 0x184AD42BAC8>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=961x1200 at 0x184ABAFE3C8>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1000x500 at 0x184ABE6A550>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1000x500 at 0x184ABAFE4E0>


In [4]:
with open("output.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(rgblist)

In [5]:
if not os.path.exists("../gray_scale"):#make directory to put gray_scale images
    os.makedirs("../gray_scale")

In [6]:
imagelist = sorted(os.listdir())
header = "../gray_scale/"
for image in imagelist:
    try:
        img = Image.open(image).convert("L")        
        file_name, ext = image.split(".")
        img.save(header + file_name + "_gray" + "." + ext)
        print(img)
    except Exception as inst:
        print(inst)
        continue

<PIL.Image.Image image mode=L size=1920x1200 at 0x184AD4BD2B0>
<PIL.Image.Image image mode=L size=961x1200 at 0x184AD49D668>
<PIL.Image.Image image mode=L size=1000x500 at 0x184AD49D6A0>
<PIL.Image.Image image mode=L size=1000x500 at 0x184AD4BD2B0>
<PIL.Image.Image image mode=L size=1024x1536 at 0x184AD49D470>
<PIL.Image.Image image mode=L size=1920x1200 at 0x184AD49DCF8>
<PIL.Image.Image image mode=L size=1920x1200 at 0x184AD4BD2B0>
cannot identify image file 'output.csv'


In [7]:
gray_images = os.listdir("../gray_scale")
header = "../gray_scale/"
graylist = []
for image in imagelist[:4]:
    imagename, ext = image.split(".")
    
    try:
        im = Image.open(header + imagename + "_gray." + ext)
        print(im)
        pix = im.load()        
        x = im.size[0]#gettin x
        y = im.size[1]#getting y
        
        for i in range(x):
            for j in range(y):
                graylist.append([pix[i, j]])#grayscale images output only the grayscale
    except Exception as inst:
        print(inst)
        continue
        

<PIL.JpegImagePlugin.JpegImageFile image mode=L size=1920x1200 at 0x184AD49DCF8>
<PIL.JpegImagePlugin.JpegImageFile image mode=L size=961x1200 at 0x184C33CA358>
<PIL.JpegImagePlugin.JpegImageFile image mode=L size=1000x500 at 0x184AD49DCF8>
<PIL.JpegImagePlugin.JpegImageFile image mode=L size=1000x500 at 0x184AD4BD080>


In [8]:
print(len(graylist))
print(len(rgblist))

4457200
4457200


In [9]:
print(graylist[:100])
with open("../gray_scale/output.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(graylist)

[[145], [145], [145], [145], [145], [145], [145], [145], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [143], [143], [143], [143], [143], [143], [143], [143], [143], [143], [143], [142], [142], [141], [141], [141], [138], [138], [137], [136], [136], [135], [134], [134], [133], [133], [133], [132], [132], [131], [131], [131], [132], [132], [131], [130], [130], [129], [128], [128], [126], [126], [125], [124], [122], [121], [120], [120], [119], [119], [120], [120], [119], [117], [116], [115], [117], [117], [117], [117], [117], [117], [117], [117], [118], [118], [118], [117], [117], [116], [116], [116], [115], [115], [115], [115]]


In [10]:
import tensorflow as tf
import pandas as pd
import numpy as np
#import necessary modules

In [11]:
print(os.getcwd())

os.chdir(maindirectory)#Changing back to python_images directory
output =pd.read_csv("./python_images/gray_scale/output.csv")
features = pd.read_csv("./python_images/iu/output.csv")


C:\Users\Jae\Documents\GitHub\rgb_to_grayscale\python_images\iu


In [12]:
print(features.head(10))
print(output.head(10))
print(features.index)
print(output.index)

#print dataframe head and translate dataframe to matrix
features = features.as_matrix()
output = output.as_matrix()


   132  161  97
0  132  161  97
1  132  161  97
2  132  161  97
3  132  161  97
4  132  161  97
5  132  161  95
6  132  161  95
7  131  160  94
8  132  161  95
9  133  162  96
   145
0  145
1  145
2  145
3  145
4  145
5  145
6  145
7  144
8  144
9  144
RangeIndex(start=0, stop=4457199, step=1)
RangeIndex(start=0, stop=4457199, step=1)


In [13]:
features = features.astype(np.float32)
output = output.astype(np.float32)

print(features.shape)
print(output.shape)
print(features[:10])
print(output[:10])

(4457199, 3)
(4457199, 1)
[[ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   95.]
 [ 132.  161.   95.]
 [ 131.  160.   94.]
 [ 132.  161.   95.]
 [ 133.  162.   96.]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]


In [14]:
epochs = 1000
learning_rate = 0.001
display_step = 5

In [15]:
x_ = tf.placeholder(tf.float32, shape=[None, 3], name="x-input")#4457199, 3
y_ = tf.placeholder(tf.float32, shape=[None, 1], name="y-input")

In [16]:
Theta1 = tf.Variable(tf.random_uniform([3, 16], -2, 2), name="Theta1")
Theta2 = tf.Variable(tf.random_uniform([16, 10], -2, 2), name="Theta2")
Theta3 = tf.Variable(tf.random_uniform([10, 1], -2, 2), name="Theta3")

In [17]:
Bias1 = tf.Variable(tf.zeros([1, 16]), name="Bias1")
Bias2 = tf.Variable(tf.zeros([1, 10]), name="Bias2")
Bias3 = tf.Variable(tf.zeros([1, 1]), name="Bias3")

In [18]:
layer_one = tf.add(tf.matmul(x_, Theta1), Bias1)
layer_two = tf.add(tf.matmul(layer_one, Theta2), Bias2)
pred = tf.add(tf.matmul(layer_two, Theta3), Bias3)
cost = tf.reduce_sum(tf.pow(pred - y_, 2)) / 500

In [19]:
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [20]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for j in range(epochs):
    feature_batch = []
    output_batch = []
    
    #print(sess.run(Theta1))
    for i in np.random.choice(len(features), 500):
        feature_batch.append(features[i])
        output_batch.append(output[i])
    feature_batch = np.asarray(feature_batch)
    output_batch = np.asarray(output_batch)
    sess.run(optimizer, feed_dict={x_: feature_batch, y_: output_batch})
    run_cost = sess.run(cost, feed_dict={x_: feature_batch, y_: output_batch})
    print(run_cost)
    

1.18577e+07
1.08261e+07
1.08484e+07
1.01263e+07
1.02893e+07
1.00209e+07
9.34962e+06
8.39073e+06
8.48151e+06
8.05531e+06
8.02912e+06
7.94257e+06
7.28614e+06
6.52617e+06
6.68058e+06
6.63541e+06
6.37956e+06
6.0854e+06
5.87892e+06
5.46324e+06
5.20485e+06
4.96773e+06
4.95815e+06
4.65189e+06
4.33862e+06
4.13305e+06
4.19078e+06
4.16175e+06
3.73255e+06
3.43041e+06
3.37716e+06
3.28589e+06
3.00643e+06
2.90651e+06
3.10485e+06
2.8885e+06
2.53603e+06
2.55465e+06
2.38725e+06
2.2824e+06
2.33011e+06
2.14355e+06
1.99734e+06
1.84465e+06
1.7417e+06
1.62216e+06
1.64855e+06
1.64808e+06
1.62688e+06
1.55424e+06
1.38987e+06
1.38561e+06
1.35042e+06
1.21184e+06
1.07013e+06
1.12154e+06
1.05156e+06
1.00749e+06
935077.0
970950.0
1.01861e+06
1.05799e+06
823365.0
841025.0
832766.0
741629.0
783174.0
739327.0
759364.0
749898.0
743735.0
702554.0
709704.0
667809.0
556430.0
742474.0
643397.0
565100.0
622149.0
685469.0
600349.0
635450.0
555581.0
606579.0
565556.0
575391.0
555277.0
589532.0
605691.0
556251.0
602879.0
66047

4375.58
4399.41
3736.3
3728.87
4436.23
3803.65
3733.99
4198.0
3762.85


In [21]:
print(output[:10])
print(features[:10])
print(sess.run(pred, feed_dict={x_: features[:10], y_ : output[:10]}))

[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
[[ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   95.]
 [ 132.  161.   95.]
 [ 131.  160.   94.]
 [ 132.  161.   95.]
 [ 133.  162.   96.]]
[[ 282.91439819]
 [ 282.91439819]
 [ 282.91439819]
 [ 282.91439819]
 [ 282.91439819]
 [ 286.47317505]
 [ 286.47317505]
 [ 285.5982666 ]
 [ 286.47317505]
 [ 287.34866333]]


In [22]:
epochs = 500
learning_rate = 0.001
display_step = 5

In [23]:
x_ = tf.placeholder(tf.float32, shape=[None, 3], name="x-input")#4457199, 3
y_ = tf.placeholder(tf.float32, shape=[None, 1], name="y-input")

In [24]:
Theta1 = tf.Variable(tf.random_uniform([3, 8], -1, 1), name="Theta1")
Theta2 = tf.Variable(tf.random_uniform([8, 8], -1, 1), name="Theta2")
Theta3 = tf.Variable(tf.random_uniform([8, 1], -1, 1), name="Theta3")

In [25]:
Bias1 = tf.Variable(tf.random_uniform([1, 8], -1, 1), name="Bias1")
Bias2 = tf.Variable(tf.random_uniform([1, 8], -1, 1), name="Bias2")
Bias3 = tf.Variable(tf.random_uniform([1, 1], -1, 1), name="Bias3")

In [26]:
layer_one = tf.add(tf.matmul(x_, Theta1), Bias1)
layer_two = tf.add(tf.matmul(layer_one, Theta2), Bias2)
pred = tf.add(tf.matmul(layer_two, Theta3), Bias3)
cost = tf.reduce_sum(tf.pow(pred - y_, 2))
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [27]:
init = tf.global_variables_initializer()
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(epochs):
        for (x, y) in zip(features[:1000], output[:1000]):
            input_x = np.asarray([x])
            input_y = np.asarray([y])
            sess.run(optimizer, feed_dict={x_: input_x, y_: input_y})
        p_cost = sess.run(cost, feed_dict={x_: features[:10], y_: output[:10]})
        print(p_cost)
        t_pred = sess.run(pred, feed_dict={x_ :features[:10], y_: output[:10]})
        print(t_pred)
        print(output[:10])
    saver.save(sess, "checkpoints/image_params")

212962.0
[[ 1.02693927]
 [ 1.02693927]
 [ 1.02693927]
 [ 1.02693927]
 [ 1.02693927]
 [-3.46273041]
 [-3.46273041]
 [-4.57026672]
 [-3.46273041]
 [-2.35528564]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
137301.0
[[ 29.34619522]
 [ 29.34619522]
 [ 29.34619522]
 [ 29.34619522]
 [ 29.34619522]
 [ 25.72516251]
 [ 25.72516251]
 [ 24.58486557]
 [ 25.72516251]
 [ 26.86542511]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
96281.1
[[ 48.07824707]
 [ 48.07824707]
 [ 48.07824707]
 [ 48.07824707]
 [ 48.07824707]
 [ 45.09426117]
 [ 45.09426117]
 [ 43.9407196 ]
 [ 45.09426117]
 [ 46.24785995]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
73289.3
[[ 60.31640625]
 [ 60.31640625]
 [ 60.31640625]
 [ 60.31640625]
 [ 60.31640625]
 [ 57.8794899 ]
 [ 57.8794899 ]
 [ 56.74050522]
 [ 57.8794899 ]
 [ 59.01855087]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 14

5358.8
[[ 167.58815002]
 [ 167.58815002]
 [ 167.58815002]
 [ 167.58815002]
 [ 167.58815002]
 [ 168.08320618]
 [ 168.08320618]
 [ 167.08139038]
 [ 168.08320618]
 [ 169.08500671]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
4019.55
[[ 164.53871155]
 [ 164.53871155]
 [ 164.53871155]
 [ 164.53871155]
 [ 164.53871155]
 [ 164.9306488 ]
 [ 164.9306488 ]
 [ 163.92996216]
 [ 164.9306488 ]
 [ 165.93136597]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
2922.85
[[ 161.63336182]
 [ 161.63336182]
 [ 161.63336182]
 [ 161.63336182]
 [ 161.63336182]
 [ 161.92886353]
 [ 161.92886353]
 [ 160.9289093 ]
 [ 161.92886353]
 [ 162.92883301]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
2055.11
[[ 158.91529846]
 [ 158.91529846]
 [ 158.91529846]
 [ 158.91529846]
 [ 158.91529846]
 [ 159.12236023]
 [ 159.12236023]
 [ 158.12287903]
 [ 159.12236023]
 [ 160.12184143]]
[[ 145.]
 [ 

6.06663
[[ 144.29789734]
 [ 144.29789734]
 [ 144.29789734]
 [ 144.29789734]
 [ 144.29789734]
 [ 144.13212585]
 [ 144.13212585]
 [ 143.12141418]
 [ 144.13212585]
 [ 145.14285278]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
6.15581
[[ 144.28868103]
 [ 144.28868103]
 [ 144.28868103]
 [ 144.28868103]
 [ 144.28868103]
 [ 144.12312317]
 [ 144.12312317]
 [ 143.11250305]
 [ 144.12312317]
 [ 145.13371277]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
6.17778
[[ 144.28630066]
 [ 144.28630066]
 [ 144.28630066]
 [ 144.28630066]
 [ 144.28630066]
 [ 144.12117004]
 [ 144.12117004]
 [ 143.110672  ]
 [ 144.12117004]
 [ 145.13166809]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
6.26016
[[ 144.27796936]
 [ 144.27796936]
 [ 144.27796936]
 [ 144.27796936]
 [ 144.27796936]
 [ 144.11303711]
 [ 144.11303711]
 [ 143.10264587]
 [ 144.11303711]
 [ 145.12342834]]
[[ 145.]
 [

7.71356
[[ 144.14692688]
 [ 144.14692688]
 [ 144.14692688]
 [ 144.14692688]
 [ 144.14692688]
 [ 143.99008179]
 [ 143.99008179]
 [ 142.98144531]
 [ 143.99008179]
 [ 144.99873352]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
7.4922
[[ 144.16435242]
 [ 144.16435242]
 [ 144.16435242]
 [ 144.16435242]
 [ 144.16435242]
 [ 144.00857544]
 [ 144.00857544]
 [ 142.99993896]
 [ 144.00857544]
 [ 145.01716614]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
7.22328
[[ 144.18643188]
 [ 144.18643188]
 [ 144.18643188]
 [ 144.18643188]
 [ 144.18643188]
 [ 144.03143311]
 [ 144.03143311]
 [ 143.02282715]
 [ 144.03143311]
 [ 145.04005432]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
7.00516
[[ 144.20483398]
 [ 144.20483398]
 [ 144.20483398]
 [ 144.20483398]
 [ 144.20483398]
 [ 144.05093384]
 [ 144.05093384]
 [ 143.0423584 ]
 [ 144.05093384]
 [ 145.05952454]]
[[ 145.]
 [ 

4.61039
[[ 145.04449463]
 [ 145.04449463]
 [ 145.04449463]
 [ 145.04449463]
 [ 145.04449463]
 [ 144.92266846]
 [ 144.92266846]
 [ 143.91404724]
 [ 144.92266846]
 [ 145.93127441]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
4.82338
[[ 145.07881165]
 [ 145.07881165]
 [ 145.07881165]
 [ 145.07881165]
 [ 145.07881165]
 [ 144.95814514]
 [ 144.95814514]
 [ 143.94952393]
 [ 144.95814514]
 [ 145.96678162]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
4.98303
[[ 145.10198975]
 [ 145.10198975]
 [ 145.10198975]
 [ 145.10198975]
 [ 145.10198975]
 [ 144.98252869]
 [ 144.98252869]
 [ 143.97396851]
 [ 144.98252869]
 [ 145.99107361]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
5.20736
[[ 145.13238525]
 [ 145.13238525]
 [ 145.13238525]
 [ 145.13238525]
 [ 145.13238525]
 [ 145.0140686 ]
 [ 145.0140686 ]
 [ 144.00552368]
 [ 145.0140686 ]
 [ 146.02261353]]
[[ 145.]
 [

20.9847
[[ 146.04785156]
 [ 146.04785156]
 [ 146.04785156]
 [ 146.04785156]
 [ 146.04785156]
 [ 145.96621704]
 [ 145.96621704]
 [ 144.95883179]
 [ 145.96621704]
 [ 146.97358704]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
22.0976
[[ 146.08892822]
 [ 146.08892822]
 [ 146.08892822]
 [ 146.08892822]
 [ 146.08892822]
 [ 146.00868225]
 [ 146.00868225]
 [ 145.00137329]
 [ 146.00868225]
 [ 147.01602173]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
23.2872
[[ 146.13150024]
 [ 146.13150024]
 [ 146.13150024]
 [ 146.13150024]
 [ 146.13150024]
 [ 146.05265808]
 [ 146.05265808]
 [ 145.0453186 ]
 [ 146.05265808]
 [ 147.0599823 ]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
24.5878
[[ 146.17666626]
 [ 146.17666626]
 [ 146.17666626]
 [ 146.17666626]
 [ 146.17666626]
 [ 146.09916687]
 [ 146.09916687]
 [ 145.09187317]
 [ 146.09916687]
 [ 147.10646057]]
[[ 145.]
 [

64.6602
[[ 147.18505859]
 [ 147.18505859]
 [ 147.18505859]
 [ 147.18505859]
 [ 147.18505859]
 [ 147.14103699]
 [ 147.14103699]
 [ 146.13565063]
 [ 147.14103699]
 [ 148.14639282]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
66.4234
[[ 147.21998596]
 [ 147.21998596]
 [ 147.21998596]
 [ 147.21998596]
 [ 147.21998596]
 [ 147.17706299]
 [ 147.17706299]
 [ 146.17178345]
 [ 147.17706299]
 [ 148.18235779]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
68.6606
[[ 147.26370239]
 [ 147.26370239]
 [ 147.26370239]
 [ 147.26370239]
 [ 147.26370239]
 [ 147.22198486]
 [ 147.22198486]
 [ 146.2167511 ]
 [ 147.22198486]
 [ 148.22720337]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
70.3466
[[ 147.29603577]
 [ 147.29603577]
 [ 147.29603577]
 [ 147.29603577]
 [ 147.29603577]
 [ 147.25541687]
 [ 147.25541687]
 [ 146.25030518]
 [ 147.25541687]
 [ 148.26054382]]
[[ 145.]
 [

145.997
[[ 148.46939087]
 [ 148.46939087]
 [ 148.46939087]
 [ 148.46939087]
 [ 148.46939087]
 [ 148.46456909]
 [ 148.46456909]
 [ 147.46226501]
 [ 148.46456909]
 [ 149.46690369]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
149.476
[[ 148.5145874 ]
 [ 148.5145874 ]
 [ 148.5145874 ]
 [ 148.5145874 ]
 [ 148.5145874 ]
 [ 148.51109314]
 [ 148.51109314]
 [ 147.50886536]
 [ 148.51109314]
 [ 149.51330566]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
153.241
[[ 148.56291199]
 [ 148.56291199]
 [ 148.56291199]
 [ 148.56291199]
 [ 148.56291199]
 [ 148.56079102]
 [ 148.56079102]
 [ 147.55867004]
 [ 148.56079102]
 [ 149.56291199]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
156.896
[[ 148.60928345]
 [ 148.60928345]
 [ 148.60928345]
 [ 148.60928345]
 [ 148.60928345]
 [ 148.60839844]
 [ 148.60839844]
 [ 147.60639954]
 [ 148.60839844]
 [ 149.61044312]]
[[ 145.]
 [

254.639
[[ 149.69160461]
 [ 149.69160461]
 [ 149.69160461]
 [ 149.69160461]
 [ 149.69160461]
 [ 149.71766663]
 [ 149.71766663]
 [ 148.71881104]
 [ 149.71766663]
 [ 150.71655273]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
257.606
[[ 149.7208252 ]
 [ 149.7208252 ]
 [ 149.7208252 ]
 [ 149.7208252 ]
 [ 149.7208252 ]
 [ 149.74751282]
 [ 149.74751282]
 [ 148.7487793 ]
 [ 149.74751282]
 [ 150.7462616 ]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
260.637
[[ 149.7505188 ]
 [ 149.7505188 ]
 [ 149.7505188 ]
 [ 149.7505188 ]
 [ 149.7505188 ]
 [ 149.77784729]
 [ 149.77784729]
 [ 148.77919006]
 [ 149.77784729]
 [ 150.77642822]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
263.453
[[ 149.7779541 ]
 [ 149.7779541 ]
 [ 149.7779541 ]
 [ 149.7779541 ]
 [ 149.7779541 ]
 [ 149.80583191]
 [ 149.80583191]
 [ 148.80734253]
 [ 149.80583191]
 [ 150.80429077]]
[[ 145.]
 [

319.028
[[ 150.29420471]
 [ 150.29420471]
 [ 150.29420471]
 [ 150.29420471]
 [ 150.29420471]
 [ 150.32804871]
 [ 150.32804871]
 [ 149.33387756]
 [ 150.32804871]
 [ 151.32217407]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
319.963
[[ 150.3026123 ]
 [ 150.3026123 ]
 [ 150.3026123 ]
 [ 150.3026123 ]
 [ 150.3026123 ]
 [ 150.33631897]
 [ 150.33631897]
 [ 149.34233093]
 [ 150.33631897]
 [ 151.33027649]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
320.744
[[ 150.30963135]
 [ 150.30963135]
 [ 150.30963135]
 [ 150.30963135]
 [ 150.30963135]
 [ 150.34318542]
 [ 150.34318542]
 [ 149.34936523]
 [ 150.34318542]
 [ 151.33700562]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
321.638
[[ 150.31767273]
 [ 150.31767273]
 [ 150.31767273]
 [ 150.31767273]
 [ 150.31767273]
 [ 150.3510437 ]
 [ 150.3510437 ]
 [ 149.35742188]
 [ 150.3510437 ]
 [ 151.34468079]]
[[ 145.]
 [

316.994
[[ 150.28392029]
 [ 150.28392029]
 [ 150.28392029]
 [ 150.28392029]
 [ 150.28392029]
 [ 150.30322266]
 [ 150.30322266]
 [ 149.31452942]
 [ 150.30322266]
 [ 151.29190063]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
316.515
[[ 150.28004456]
 [ 150.28004456]
 [ 150.28004456]
 [ 150.28004456]
 [ 150.28004456]
 [ 150.29856873]
 [ 150.29856873]
 [ 149.31004333]
 [ 150.29856873]
 [ 151.28712463]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
316.589
[[ 150.28108215]
 [ 150.28108215]
 [ 150.28108215]
 [ 150.28108215]
 [ 150.28108215]
 [ 150.29891968]
 [ 150.29891968]
 [ 149.31051636]
 [ 150.29891968]
 [ 151.28730774]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
315.988
[[ 150.27609253]
 [ 150.27609253]
 [ 150.27609253]
 [ 150.27609253]
 [ 150.27609253]
 [ 150.29319763]
 [ 150.29319763]
 [ 149.30499268]
 [ 150.29319763]
 [ 151.28141785]]
[[ 145.]
 [

296.505
[[ 150.10949707]
 [ 150.10949707]
 [ 150.10949707]
 [ 150.10949707]
 [ 150.10949707]
 [ 150.10678101]
 [ 150.10678101]
 [ 149.123703  ]
 [ 150.10678101]
 [ 151.08988953]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
294.686
[[ 150.09318542]
 [ 150.09318542]
 [ 150.09318542]
 [ 150.09318542]
 [ 150.09318542]
 [ 150.0894928 ]
 [ 150.0894928 ]
 [ 149.1065979 ]
 [ 150.0894928 ]
 [ 151.0723877 ]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
292.796
[[ 150.0761261 ]
 [ 150.0761261 ]
 [ 150.0761261 ]
 [ 150.0761261 ]
 [ 150.0761261 ]
 [ 150.07150269]
 [ 150.07150269]
 [ 149.08879089]
 [ 150.07150269]
 [ 151.05418396]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
291.547
[[ 150.06498718]
 [ 150.06498718]
 [ 150.06498718]
 [ 150.06498718]
 [ 150.06498718]
 [ 150.05943298]
 [ 150.05943298]
 [ 149.07693481]
 [ 150.05943298]
 [ 151.04196167]]
[[ 145.]
 [

223.031
[[ 149.40049744]
 [ 149.40049744]
 [ 149.40049744]
 [ 149.40049744]
 [ 149.40049744]
 [ 149.36184692]
 [ 149.36184692]
 [ 148.38487244]
 [ 149.36184692]
 [ 150.33885193]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
220.128
[[ 149.37011719]
 [ 149.37011719]
 [ 149.37011719]
 [ 149.37011719]
 [ 149.37011719]
 [ 149.3301239 ]
 [ 149.3301239 ]
 [ 148.35331726]
 [ 149.3301239 ]
 [ 150.30691528]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
217.793
[[ 149.34564209]
 [ 149.34564209]
 [ 149.34564209]
 [ 149.34564209]
 [ 149.34564209]
 [ 149.30433655]
 [ 149.30433655]
 [ 148.32769775]
 [ 149.30433655]
 [ 150.2809906 ]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
214.825
[[ 149.31419373]
 [ 149.31419373]
 [ 149.31419373]
 [ 149.31419373]
 [ 149.31419373]
 [ 149.27148438]
 [ 149.27148438]
 [ 148.29507446]
 [ 149.27148438]
 [ 150.2479248 ]]
[[ 145.]
 [

138.108
[[ 148.40692139]
 [ 148.40692139]
 [ 148.40692139]
 [ 148.40692139]
 [ 148.40692139]
 [ 148.32389832]
 [ 148.32389832]
 [ 147.35246277]
 [ 148.32389832]
 [ 149.29533386]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
135.633
[[ 148.3737793 ]
 [ 148.3737793 ]
 [ 148.3737793 ]
 [ 148.3737793 ]
 [ 148.3737793 ]
 [ 148.2893219 ]
 [ 148.2893219 ]
 [ 147.31803894]
 [ 148.2893219 ]
 [ 149.26060486]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
133.243
[[ 148.34152222]
 [ 148.34152222]
 [ 148.34152222]
 [ 148.34152222]
 [ 148.34152222]
 [ 148.25558472]
 [ 148.25558472]
 [ 147.28445435]
 [ 148.25558472]
 [ 149.22671509]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
130.55
[[ 148.30474854]
 [ 148.30474854]
 [ 148.30474854]
 [ 148.30474854]
 [ 148.30474854]
 [ 148.21725464]
 [ 148.21725464]
 [ 147.24629211]
 [ 148.21725464]
 [ 149.18823242]]
[[ 145.]
 [ 

68.926
[[ 147.3210907 ]
 [ 147.3210907 ]
 [ 147.3210907 ]
 [ 147.3210907 ]
 [ 147.3210907 ]
 [ 147.18991089]
 [ 147.18991089]
 [ 146.22271729]
 [ 147.18991089]
 [ 148.15707397]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
67.1961
[[ 147.28779602]
 [ 147.28779602]
 [ 147.28779602]
 [ 147.28779602]
 [ 147.28779602]
 [ 147.15519714]
 [ 147.15519714]
 [ 146.18817139]
 [ 147.15519714]
 [ 148.12225342]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
65.4556
[[ 147.25398254]
 [ 147.25398254]
 [ 147.25398254]
 [ 147.25398254]
 [ 147.25398254]
 [ 147.11967468]
 [ 147.11967468]
 [ 146.15275574]
 [ 147.11967468]
 [ 148.0866394 ]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
63.8176
[[ 147.22163391]
 [ 147.22163391]
 [ 147.22163391]
 [ 147.22163391]
 [ 147.22163391]
 [ 147.08587646]
 [ 147.08587646]
 [ 146.11903381]
 [ 147.08587646]
 [ 148.05273438]]
[[ 145.]
 [ 

27.5198
[[ 146.3374176 ]
 [ 146.3374176 ]
 [ 146.3374176 ]
 [ 146.3374176 ]
 [ 146.3374176 ]
 [ 146.16172791]
 [ 146.16172791]
 [ 145.19793701]
 [ 146.16172791]
 [ 147.12554932]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
26.5771
[[ 146.3074646 ]
 [ 146.3074646 ]
 [ 146.3074646 ]
 [ 146.3074646 ]
 [ 146.3074646 ]
 [ 146.13046265]
 [ 146.13046265]
 [ 145.16676331]
 [ 146.13046265]
 [ 147.09413147]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
25.4934
[[ 146.27218628]
 [ 146.27218628]
 [ 146.27218628]
 [ 146.27218628]
 [ 146.27218628]
 [ 146.09376526]
 [ 146.09376526]
 [ 145.13026428]
 [ 146.09376526]
 [ 147.05731201]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
24.6366
[[ 146.24368286]
 [ 146.24368286]
 [ 146.24368286]
 [ 146.24368286]
 [ 146.24368286]
 [ 146.06413269]
 [ 146.06413269]
 [ 145.10073853]
 [ 146.06413269]
 [ 147.0275116 ]]
[[ 145.]
 [

5.38291
[[ 145.25390625]
 [ 145.25390625]
 [ 145.25390625]
 [ 145.25390625]
 [ 145.25390625]
 [ 145.03533936]
 [ 145.03533936]
 [ 144.07554626]
 [ 145.03533936]
 [ 145.99510193]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
5.06936
[[ 145.21817017]
 [ 145.21817017]
 [ 145.21817017]
 [ 145.21817017]
 [ 145.21817017]
 [ 144.99824524]
 [ 144.99824524]
 [ 144.03860474]
 [ 144.99824524]
 [ 145.957901  ]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
4.82809
[[ 145.18849182]
 [ 145.18849182]
 [ 145.18849182]
 [ 145.18849182]
 [ 145.18849182]
 [ 144.9672699 ]
 [ 144.9672699 ]
 [ 144.00773621]
 [ 144.9672699 ]
 [ 145.92681885]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]
4.5776
[[ 145.15480042]
 [ 145.15480042]
 [ 145.15480042]
 [ 145.15480042]
 [ 145.15480042]
 [ 144.93231201]
 [ 144.93231201]
 [ 143.97288513]
 [ 144.93231201]
 [ 145.89173889]]
[[ 145.]
 [ 

In [270]:
from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
os.chdir(maindirectory + "/python_images/iu")
print(os.listdir())
first_test = os.path.join(os.getcwd(), os.listdir()[0])
print(first_test)

def get_image_array(file_name):
    img = Image.open(file_name)
    img = np.array(img)
    original_shape = img.shape
    print("Original image shape", img.shape)
    img = img.reshape((img.shape[0] * img.shape[1], 3))
    img.astype(float)
    
    return img, original_shape

def construct_image_direct(array, shape, file_name):
    new_shape = (shape[0], shape[1], 1)
    array = array.reshape(shape[:-1])
    array = np.asarray(array, dtype=np.uint8)
    parent = os.path.abspath(os.path.join(os.path.dirname(file_name), os.pardir))
    generated_path = os.path.join(parent, "generated")
    img = Image.fromarray(array, "L")
    img.save(os.path.join(generated_path, os.path.basename(file_name)))
    
def construct_image(array, shape, file_name):
    empty = Image.new("L", shape[:-1][::-1])
    empty = np.array(empty)
    array = array.reshape(shape[:-1])
    for x in range(shape[0]):
        for y in range(shape[1]):
            #print(array[x][y])
            empty[x][y] = int(array[x][y])
    img = Image.fromarray(empty, "L")
    parent = os.path.abspath(os.path.join(os.path.dirname(file_name), os.pardir))
    generated_path = os.path.join(parent, "generated")
    img.save(os.path.join(generated_path, os.path.basename(file_name)))
    
def get_grayscale(file_name):
    img = Image.open(file_name)
    img = np.array(img)
    empty = Image.new("L", img.shape[::-1][1:])
    empty = np.array(empty)
    
    img = np.array(img)
    for x in range(img.shape[0]):
        for y in range(img.shape[1]):
            empty[x][y] = int(sum(img[x][y]) / 3)
            
    print(img.shape)
    ret = Image.fromarray(empty, "L")
    ret.save("test.jpg")
            
#get_grayscale(first_test)

['4WOvMS.jpg', 'CsscgpbUAAARr2l.jpg', 'iu.jpg', 'IU_1476317492_af_org.jpg', 'IU_1489714957_af_org.jpg', 'kYlOg8.jpg', 'maxresdefault.jpg', 'output.csv']
C:\Users\Jae\Documents\GitHub\rgb_to_grayscale\python_images\iu\4WOvMS.jpg


In [ ]:
os.chdir(maindirectory)
saver = tf.train.Saver()
loaded_graph = tf.Graph()
with tf.Session() as sess:
    saver.restore(sess, tf.train.latest_checkpoint("checkpoints"))
    graph = tf.get_default_graph()
    Theta1 = graph.get_tensor_by_name("Theta1:0")
    for file in os.listdir(maindirectory + "/python_images/iu"):
        try:
            print("Starting!")
            filepath = os.path.join(maindirectory, "python_images/iu")
            
            filepath = os.path.join(filepath, file)
            input, shape = get_image_array(filepath)
            t_pred = sess.run(pred, feed_dict={x_ :input})
            
            construct_image_direct(t_pred, shape, filepath)
            #construct_image(t_pred, shape, filepath)
        except Exception as e:
            print(e)
            continue
    


INFO:tensorflow:Restoring parameters from checkpoints\image_params
Starting!
Original image shape (1200, 1920, 3)


In [234]:
im = Image.open('output.jpg')
im = np.array(im)
df = pd.DataFrame(im)
df.to_csv("test.csv")
