In [1]:
from PIL import Image
import os
import csv

In [2]:
maindirectory = os.getcwd()
print(os.getcwd())
#os.chdir("./python_images/iu")#set current directory to the directory of images

C:\Users\USER\Documents\GitHub\rgb_to_grayscale


In [3]:
os.chdir(maindirectory + "/python_images/iu")
imagelist = sorted(os.listdir())
rgblist = []

for image in imagelist[:4]:
    try:
        im = Image.open(image)
        pix = im.load()        
        x = im.size[0]#gettin x
        y = im.size[1]#getting y
        print(im)
        for i in range(x):
            for j in range(y):
                rgblist.append(pix[i, j])
    except:
        continue
        

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1920x1200 at 0x214980ADCC0>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=961x1200 at 0x214980AF5F8>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1000x500 at 0x21498147C50>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1000x500 at 0x21498147BE0>


In [4]:
with open("output.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(rgblist)

In [5]:
if not os.path.exists("../gray_scale"):#make directory to put gray_scale images
    os.makedirs("../gray_scale")

In [6]:
imagelist = sorted(os.listdir())
header = "../gray_scale/"
for image in imagelist:
    try:
        img = Image.open(image).convert("L")        
        file_name, ext = image.split(".")
        img.save(header + file_name + "_gray" + "." + ext)
        print(img)
    except Exception as inst:
        print(inst)
        continue

<PIL.Image.Image image mode=L size=1920x1200 at 0x21498092D30>
<PIL.Image.Image image mode=L size=961x1200 at 0x21498147D30>
<PIL.Image.Image image mode=L size=1000x500 at 0x21497077F60>
<PIL.Image.Image image mode=L size=1000x500 at 0x21498092D30>
<PIL.Image.Image image mode=L size=1024x1536 at 0x214980AD940>
<PIL.Image.Image image mode=L size=1920x1200 at 0x21497077F60>
<PIL.Image.Image image mode=L size=1920x1200 at 0x21498092D30>
cannot identify image file 'output.csv'


In [7]:
gray_images = os.listdir("../gray_scale")
header = "../gray_scale/"
graylist = []
for image in imagelist[:4]:
    imagename, ext = image.split(".")
    
    try:
        im = Image.open(header + imagename + "_gray." + ext)
        print(im)
        pix = im.load()        
        x = im.size[0]#gettin x
        y = im.size[1]#getting y
        
        for i in range(x):
            for j in range(y):
                graylist.append([pix[i, j]])#grayscale images output only the grayscale
    except Exception as inst:
        print(inst)
        continue
        

<PIL.JpegImagePlugin.JpegImageFile image mode=L size=1920x1200 at 0x214ADF9EEF0>
<PIL.JpegImagePlugin.JpegImageFile image mode=L size=961x1200 at 0x214ADF95630>
<PIL.JpegImagePlugin.JpegImageFile image mode=L size=1000x500 at 0x21498092EF0>
<PIL.JpegImagePlugin.JpegImageFile image mode=L size=1000x500 at 0x21498092F98>


In [9]:
print(len(graylist))
print(len(rgblist))

4457200
4457200


In [10]:
print(graylist[:100])
with open("../gray_scale/output.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(graylist)

[[145], [145], [145], [145], [145], [145], [145], [145], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [144], [143], [143], [143], [143], [143], [143], [143], [143], [143], [143], [143], [142], [142], [141], [141], [141], [138], [138], [137], [136], [136], [135], [134], [134], [133], [133], [133], [132], [132], [131], [131], [131], [132], [132], [131], [130], [130], [129], [128], [128], [126], [126], [125], [124], [122], [121], [120], [120], [119], [119], [120], [120], [119], [117], [116], [115], [117], [117], [117], [117], [117], [117], [117], [117], [118], [118], [118], [117], [117], [116], [116], [116], [115], [115], [115], [115]]


In [11]:
import tensorflow as tf
import pandas as pd
import numpy as np
#import necessary modules

In [12]:
print(os.getcwd())

os.chdir(maindirectory)#Changing back to python_images directory
output =pd.read_csv("./python_images/gray_scale/output.csv")
features = pd.read_csv("./python_images/iu/output.csv")


C:\Users\USER\Documents\GitHub\rgb_to_grayscale\python_images\iu


In [13]:
print(features.head(10))
print(output.head(10))
print(features.index)
print(output.index)

#print dataframe head and translate dataframe to matrix
features = features.as_matrix()
output = output.as_matrix()


   132  161  97
0  132  161  97
1  132  161  97
2  132  161  97
3  132  161  97
4  132  161  97
5  132  161  95
6  132  161  95
7  131  160  94
8  132  161  95
9  133  162  96
   145
0  145
1  145
2  145
3  145
4  145
5  145
6  145
7  144
8  144
9  144
RangeIndex(start=0, stop=4457199, step=1)
RangeIndex(start=0, stop=4457199, step=1)


In [14]:
features = features.astype(np.float32)
output = output.astype(np.float32)

print(features.shape)
print(output.shape)
print(features[:10])
print(output[:10])

(4457199, 3)
(4457199, 1)
[[ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   97.]
 [ 132.  161.   95.]
 [ 132.  161.   95.]
 [ 131.  160.   94.]
 [ 132.  161.   95.]
 [ 133.  162.   96.]]
[[ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 145.]
 [ 144.]
 [ 144.]
 [ 144.]]


In [27]:
x_ = tf.placeholder(tf.float32, shape=[None, 3], name="x-input")#4457199, 3
y_ = tf.placeholder(tf.float32,shape=[None], name="y-input")

In [28]:

Theta1 = tf.Variable(tf.random_uniform([3, 16], -2, 2), name="Theta1")
Theta2 = tf.Variable(tf.random_uniform([16, 10], -2, 2), name="Theta2")
Theta3 = tf.Variable(tf.random_uniform([10, 1], -2, 2), name="Theta3")
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(Theta1))

AttributeError: module 'tensorflow' has no attribute 'random_in'

In [18]:
Bias1 = tf.Variable(tf.zeros([16]), name="Bias1")
Bias2 = tf.Variable(tf.zeros([10]), name="Bias2")
Bias3 = tf.Variable(tf.zeros(1), name="Bias3")

In [19]:
A2 = tf.nn.sigmoid(tf.matmul(x_, Theta1) + Bias1)
A3 = tf.nn.relu(tf.matmul(A2, Theta2) + Bias2)
Output = tf.matmul(A3, Theta3) + Bias3

In [20]:
cost = tf.reduce_mean(tf.square(y_ - Output))

In [21]:
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [22]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for j in range(20):
    feature_batch = []
    output_batch = []
    
    #print(sess.run(Theta1))
    for i in np.random.choice(len(features), 500):
        feature_batch.append(features[i])
        output_batch.append(output[i][0])        
    sess.run([cost, Output], feed_dict={x_: feature_batch, y_ : output_batch})
    feature_batch = np.array(feature_batch)
    output_batch = np.array(output_batch)
    sess.run(train_step, feed_dict={x_: feature_batch, y_ : output_batch})
    print(sess.run(cost, feed_dict={x_: feature_batch, y_: output_batch}))
    #print(sess.run(Output, feed_dict={x_: feature_batch, y_: output_batch}))
    #print(sess.run(y_, feed_dict={x_: feature_batch, y_: output_batch[:,None]}))
    
#for i in range(len(features)):
    #feature_batch, label_batch = tf.train.shuffle_batch([features, output], batch_size=40, capacity=5000, min_after_dequeue=1000)
    #for i in range(10000):
#    sess.run(train_step, feed_dict={x_: features[i][None,:], y_ : y[i]})
       #print(sess.run(Output, feed_dict={x_: features[:1000]}))
       #print(sess.run(cost, feed_dict={x_: features[0][None,:], y_ : output[0][None,:]}))    


    #print(sess.run(Output, feed_dict={x_: features[:10000]}))

6721.52
43046.6
28215.4
19447.2
857760.0
34750.6
30471.0
31397.3
29050.4
28033.7
28107.7
26258.2
24898.6
24598.0
23659.0
23151.6
22074.3
21282.0
22746.8
20134.2


In [26]:
import random

print(sess.run(Theta1))
for x in np.random.choice(len(features), 3):
    print(sess.run(Output, feed_dict={x_: features[x][None,:]}))
    print(output[x])
    #print(sess.run(Output, feed_dict={x_: features[:10000]}))

[[ -4.86760044e+00  -7.85783815e+00   1.61542714e-01  -3.95491266e+00
   -1.28263319e+00  -9.72900987e-01   2.00020507e-01  -2.30180645e+00
   -5.10271120e+00   1.51889124e+01  -1.24187546e+01  -2.88410139e+00
   -1.54920340e+00   1.93875873e+00  -2.14538050e+00   1.02147901e+00]
 [ -5.67728186e+00  -9.56535912e+00  -4.12249297e-01  -7.46914530e+00
    4.57997620e-01  -1.27564800e+00  -1.80306816e+00  -7.52973557e-03
   -3.58991528e+00   2.40540719e+00  -3.56196642e-01   5.51048994e-01
    1.03479278e+00   1.33015203e+00  -5.23237288e-02  -1.53772354e+00]
 [  1.37379861e+00  -8.91621590e+00  -2.56621981e+00  -8.09528923e+00
   -1.88233781e+00  -4.65826213e-01  -1.76004791e+00  -2.61368251e+00
   -3.17989063e+00   1.69481297e+01  -1.31461077e+01  -9.79778051e-01
   -1.33204365e+00   1.75320446e+00  -1.58683419e+00  -1.00464308e+00]]
[[ 33.79571915]]
[ 118.]
[[ 33.79571915]]
[ 107.]
[[ 33.79571915]]
[ 128.]


In [29]:
import tensorflow as tf
import numpy as np

x_ = tf.placeholder(tf.float32, shape=[None, 3], name="x-input")#4457199, 3
y_ = tf.placeholder(tf.float32,shape=[None], name="y-input")

In [30]:

Theta1 = tf.Variable(tf.truncated_normal([3, 1], mean=0.0, stddev=0.1, dtype=tf.float32))

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(Theta1))

[[ 0.05032415]
 [ 0.05653598]
 [-0.06062362]]


In [31]:
Bias1 = tf.Variable(tf.zeros([1]), name="Bias1")

In [32]:
Output = tf.nn.bias_add(tf.matmul(x_, Theta1), Bias1)

In [33]:
cost = tf.reduce_mean(tf.square(y_ - Output))

In [34]:
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [38]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for j in range(20):
    feature_batch = []
    output_batch = []
    
    #print(sess.run(Theta1))
    for i in np.random.choice(len(features), 500):
        feature_batch.append(features[i])
        output_batch.append(output[i][0])        
    sess.run([cost, Output], feed_dict={x_: feature_batch, y_ : output_batch})
    feature_batch = np.array(feature_batch)
    output_batch = np.array(output_batch)
    sess.run(train_step, feed_dict={x_: feature_batch, y_ : output_batch})
    print(sess.run(cost, feed_dict={x_: feature_batch, y_: output_batch}))
    #print(sess.run(Output, feed_dict={x_: feature_batch, y_: output_batch}))
    #print(sess.run(y_, feed_dict={x_: feature_batch, y_: output_batch[:,None]}))
    
#for i in range(len(features)):
    #feature_batch, label_batch = tf.train.shuffle_batch([features, output], batch_size=40, capacity=5000, min_after_dequeue=1000)
    #for i in range(10000):
#    sess.run(train_step, feed_dict={x_: features[i][None,:], y_ : y[i]})
       #print(sess.run(Output, feed_dict={x_: features[:1000]}))
       #print(sess.run(cost, feed_dict={x_: features[0][None,:], y_ : output[0][None,:]}))    


    #print(sess.run(Output, feed_dict={x_: features[:10000]}))

2.88026e+10
9.93083e+16
3.13122e+23
1.01834e+30
inf
inf
inf
inf
inf
inf
inf
inf
nan
nan
nan
nan
nan
nan
nan
nan


In [332]:
import random

print(sess.run(Theta1))
for x in np.random.choice(len(features), 3):
    print(sess.run(Output, feed_dict={x_: features[x][None,:]})[0])
    print(output[x])
    #print(sess.run(Output, feed_dict={x_: features[:10000]}))

[[  8.68002951e-01   1.95123959e+01  -1.22382021e+00   1.51659894e+00
    3.52744980e+01  -2.85319877e+00  -4.25192378e-02  -5.35740197e-01
   -2.66057581e-01  -4.19583702e+00  -1.54616559e+00   2.76537442e+00
   -1.91497135e+01   2.81886234e+01  -6.32947636e+00  -1.68611202e+01]
 [  1.83685100e+00   3.35399017e+01   2.68373668e-01  -9.62459683e-01
    4.45806923e+01  -3.17642021e+00   2.04028106e+00  -8.27278554e-01
   -1.08303785e+00  -1.64490914e+00  -6.21225119e-01  -5.26051760e-01
   -7.06332321e+01   1.21655455e+01  -6.41418123e+00  -7.41836262e+00]
 [  1.10960984e+00   5.10573921e+01  -4.05697912e-01   1.92041790e+00
    2.13867664e+01  -1.95715308e+00   4.69009131e-01  -2.66462624e-01
   -3.95343840e-01  -8.94993782e-01   8.28943402e-02  -1.17099547e+00
   -1.26678833e+02   1.23433256e+01  -4.62833786e+00  -1.35383902e+01]]
[ 40.77082825]
[ 155.]
[ 40.77082825]
[ 250.]
[ 40.77082825]
[ 237.]
